### ISSUE TITLE
add dot learn file

### ISSUE THREAD

**Issue by ktravers** [learn-co-curriculum/why-redux#6]
hey @gj, can we add a dot learn file to this repo? it's a requirement for all published lessons on Learn: https://github.com/learn-co/learn-lint

**Comment by gj** [comment]
Definitely can, but it appears a number of the Redux lessons don't have it. Should probably make it part of a wider sweep.

cc: @jmburges

**Comment by ktravers** [comment]
@gj yeah, there's a whole bunch. 

if you use the learn-co gem when creating labs (https://github.com/learn-co/learn-generate), then all this required stuff gets created for you. i know our curriculum writers used to use it regularly in the past, but maybe it's fallen out of favor

**Comment by gj** [comment]
@ktravers if it's going to come back in favor, it'll require a sizable overhaul. The JS generator sets up a Jasmine project and adds jQuery 1.8.3, among myriad other sins. 😆

FWIW, I haven't found myself pining for a gem to speed the creation of new labs. It's a pretty quick, painless process as-is. Not sure what kind of direction / templates were given to the group that created the Redux curriculum, but we can definitely highlight the importance of the `.learn` file (and of following a well-constructed template, generally) for future curriculum writers.

Additionally, if we decide on a wider sweep, I've noticed a ton of labs have very generic `.learn` files, [e.g.](https://github.com/learn-co-curriculum/javascript-objects-lab/blob/master/.learn):
```
tags:
  - javascript
languages:
  - javascript
resources:
  - 1
```
[and](https://github.com/learn-co-curriculum/javascript-arrays-lab/blob/master/.learn):
```
tags:
  - javascript
languages:
  - javascript
resources:
  - 1
```

**Comment by ktravers** [comment]
@gj less concerned about the generic `.learn` files. not all our labs have fancy stuff going on, and that's fine. 

more concerned about keeping our curriculum consistent and valid, which is the main benefit of using the generator gem. it'd save us a lot of bug reports / JIRA tickets.

at minimum, it'd be good to have curriculum writers running their stuff through the [linter](https://github.com/learn-co/learn-lint) and then actually addressing anything that gets flagged. right now it's not strict; it won't block you from publishing an invalid lab. so maybe that's the better long term solution... hook up the linter to commits + make it blocking

**Comment by gj** [comment]
@ktravers I think making the linter blocking is a great idea.

The [gem](https://github.com/learn-co/learn-lint) (and the [Heroku CI server that depends on it](https://learn-linter-ci.herokuapp.com/)) are both in need of an update. I have an [open PR](https://github.com/learn-co/learn-lint/pull/7) on the gem that covers the bare minimum to bring it back up to speed, but it should really get a more complete makeover before it starts blocking curriculum deployments. The `CONTRIBUTING.md` and `LICENSE.md` checks are fine, but the `.learn` one is pretty brittle and the `README.md` one doesn't actually check anything except the beginning and ending backticks of code snippets.

Also, I'm not sure who has access to the Heroku app. Maybe a question for @adamjonas ?

**Comment by adamjonas** [comment]
Are people using the linter? Is it worth investing in?

**Comment by gj** [comment]
Not that I'm aware of @adamjonas. The CI server checks every PR against a `learn-co-curriculum` repo, but, as @ktravers said above, it doesn't block deployments.

It certainly wouldn't be a wasted investment, but I'm not sure how high on the priority list it should fall. At a minimum, I'd love it if the README.md linter actually checked the entire file for proper GitHub-flavored markdown syntax (with an exception carved out for our custom-rolled quizzes).

**Comment by maxwellbenton** [comment]
Hey all,

I've added in .learn files that were missing on redux repositories and am closing up this issue in preparation for v6.
